[package]
name = "tty"
version = "0.1.0"
authors = ["Ian Shehadeh <IanShehadeh2020@gmail.com>"]

[dependencies]
nix = "0.11.0"
lazy_static = "1.0"
failure = "0.1.1"
failure_derive = "0.1.1"
terminfo = { path = "./terminfo", version = "0.1.0" }
